import React, {useEffect, useState} from 'react';
import BaseLayout from "../components/container/BaseLayout";
import Head from "next/head";
import firebaseApp from "../net/firebaseApp";
import {collection, getFirestore, onSnapshot} from 'firebase/firestore'


const firebaseDb = getFirestore(firebaseApp)
const orders = collection(firebaseDb, 'orders')

export default function Home() {
    const [list, setList] = useState([])

    // onSnapshot을 활용한 실시간 데이터 연동
    useEffect(() => {
        return onSnapshot(orders, docs => {
            // setList(docs.map(doc => ({id: doc.id, ...doc.data()})))
            const newList=[];
            docs.forEach(doc => newList.push({id: doc.id, ...doc.data()}))
            setList(newList)
        })
    }, [])

    return (
        <BaseLayout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>주문 확인</h1>

            {list.map(order => (
                <li key={order.id}>{order.name} / {JSON.stringify(order.items)} / {order.status}</li>
            ))}
        </BaseLayout>
    )
}
